// <copyright file="ColumnRendererTest.cs" company="Simon Bridewell">
// Copyright (c) Simon Bridewell.
// Released under the MIT license - see LICENSE.txt in the repository root.
// </copyright>

namespace Sde.MazeGame.Test.Painters.Pov
{
    using System.Diagnostics.CodeAnalysis;
    using FluentAssertions;
    using Moq;
    using Sde.ConsoleGems.Consoles;
    using Sde.ConsoleGems.FullScreen;
    using Sde.ConsoleGems.Text;
    using Sde.MazeGame.Models;
    using Sde.MazeGame.Painters.Pov;
    using Xunit.Abstractions;

    /// <summary>
    /// Unit tests for the <see cref="ColumnRenderer"/> class.
    /// </summary>
    public class ColumnRendererTest(ITestOutputHelper output)
    {
        [SuppressMessage(
            "Style",
            "IDE1006:Naming Styles",
            Justification = "Contradicts SA1313 which is a warning rather than info")]
        private record RenderColumnTestCase(
            bool isPerpendicular,
            int screenX,
            string[] expectedCharacters);

        /// <summary>
        /// Gets the names of the test cases for the RenderColumn method.
        /// </summary>
        public static TheoryData<string> RenderColumnTestData
            => new (RenderColumnTestCases.Keys);

        /// <summary>
        /// Gets the test cases for the RenderColumn method.
        /// </summary>
        [SuppressMessage(
            "StyleCop.CSharp.ReadabilityRules",
            "SA1118:Parameter should not span multiple lines",
            Justification = "This format is nice and readable")]
        private static Dictionary<string, RenderColumnTestCase> RenderColumnTestCases
            => new ()
            {
                ["Perpendicular column 0"] = new RenderColumnTestCase(
                    isPerpendicular: true,
                    0,
                    [
                        "●                       ",
                        "▓                       ",
                        "▓                       ",
                        "▓                       ",
                        "▓                       ",
                        "▓                       ",
                        "▓                       ",
                        "▓                       ",
                        "▓                       ",
                        "▓                       ",
                        "▓                       ",
                        "▓                       ",
                        "▓                       ",
                        "▓                       ",
                        "▓                       ",
                        "▓                       ",
                        "▓                       ",
                        "▓                       ",
                        "▓                       ",
                        "▓                       ",
                        "▓                       ",
                        "▓                       ",
                        "▓                       ",
                        "○                       ",
                    ]),
                ["Perpendicular column 1"] = new RenderColumnTestCase(
                    isPerpendicular: true,
                    1,
                    [
                        " ●                      ",
                        " ●                      ",
                        " ●                      ",
                        " ●                      ",
                        " ●                      ",
                        " ▓                      ",
                        " ▓                      ",
                        " ▓                      ",
                        " ▓                      ",
                        " ▓                      ",
                        " ▓                      ",
                        " ▓                      ",
                        " ▓                      ",
                        " ▓                      ",
                        " ▓                      ",
                        " ▓                      ",
                        " ▓                      ",
                        " ▓                      ",
                        " ▓                      ",
                        " ○                      ",
                        " ○                      ",
                        " ○                      ",
                        " ○                      ",
                        " ○                      ",
                    ]),
                ["Perpendicular column 2"] = new RenderColumnTestCase(
                    isPerpendicular: true,
                    2,
                    [
                        "  ●                     ",
                        "  ●                     ",
                        "  ●                     ",
                        "  ●                     ",
                        "  ●                     ",
                        "  ▓                     ",
                        "  ▓                     ",
                        "  ▓                     ",
                        "  ▓                     ",
                        "  ▓                     ",
                        "  ▓                     ",
                        "  ▓                     ",
                        "  ▓                     ",
                        "  ▓                     ",
                        "  ▓                     ",
                        "  ▓                     ",
                        "  ▓                     ",
                        "  ▓                     ",
                        "  ▓                     ",
                        "  ○                     ",
                        "  ○                     ",
                        "  ○                     ",
                        "  ○                     ",
                        "  ○                     ",
                    ]),
                ["Perpendicular column 3"] = new RenderColumnTestCase(
                    isPerpendicular: true,
                    3,
                    [
                        "   ●                    ",
                        "   ●                    ",
                        "   ●                    ",
                        "   ●                    ",
                        "   ●                    ",
                        "   ▓                    ",
                        "   ▓                    ",
                        "   ▓                    ",
                        "   ▓                    ",
                        "   ▓                    ",
                        "   ▓                    ",
                        "   ▓                    ",
                        "   ▓                    ",
                        "   ▓                    ",
                        "   ▓                    ",
                        "   ▓                    ",
                        "   ▓                    ",
                        "   ▓                    ",
                        "   ▓                    ",
                        "   ○                    ",
                        "   ○                    ",
                        "   ○                    ",
                        "   ○                    ",
                        "   ○                    ",
                    ]),
                ["Perpendicular column 4"] = new RenderColumnTestCase(
                    isPerpendicular: true,
                    4,
                    [
                        "    ●                   ",
                        "    ●                   ",
                        "    ●                   ",
                        "    ●                   ",
                        "    ●                   ",
                        "    ▓                   ",
                        "    ▓                   ",
                        "    ▓                   ",
                        "    ▓                   ",
                        "    ▓                   ",
                        "    ▓                   ",
                        "    ▓                   ",
                        "    ▓                   ",
                        "    ▓                   ",
                        "    ▓                   ",
                        "    ▓                   ",
                        "    ▓                   ",
                        "    ▓                   ",
                        "    ▓                   ",
                        "    ○                   ",
                        "    ○                   ",
                        "    ○                   ",
                        "    ○                   ",
                        "    ○                   ",
                    ]),
                ["Perpendicular column 5"] = new RenderColumnTestCase(
                    isPerpendicular: true,
                    5,
                    [
                        "     ●                  ",
                        "     ●                  ",
                        "     ●                  ",
                        "     ●                  ",
                        "     ●                  ",
                        "     ●                  ",
                        "     ●                  ",
                        "     ●                  ",
                        "     ▓                  ",
                        "     ▓                  ",
                        "     ▓                  ",
                        "     ▓                  ",
                        "     ▓                  ",
                        "     ▓                  ",
                        "     ▓                  ",
                        "     ▓                  ",
                        "     ○                  ",
                        "     ○                  ",
                        "     ○                  ",
                        "     ○                  ",
                        "     ○                  ",
                        "     ○                  ",
                        "     ○                  ",
                        "     ○                  ",
                    ]),
                ["Perpendicular column 6"] = new RenderColumnTestCase(
                    isPerpendicular: true,
                    6,
                    [
                        "      ●                 ",
                        "      ●                 ",
                        "      ●                 ",
                        "      ●                 ",
                        "      ●                 ",
                        "      ●                 ",
                        "      ●                 ",
                        "      ●                 ",
                        "      ▓                 ",
                        "      ▓                 ",
                        "      ▓                 ",
                        "      ▓                 ",
                        "      ▓                 ",
                        "      ▓                 ",
                        "      ▓                 ",
                        "      ▓                 ",
                        "      ○                 ",
                        "      ○                 ",
                        "      ○                 ",
                        "      ○                 ",
                        "      ○                 ",
                        "      ○                 ",
                        "      ○                 ",
                        "      ○                 ",
                    ]),
                ["Perpendicular column 7"] = new RenderColumnTestCase(
                    isPerpendicular: true,
                    7,
                    [
                        "       ●                ",
                        "       ●                ",
                        "       ●                ",
                        "       ●                ",
                        "       ●                ",
                        "       ●                ",
                        "       ●                ",
                        "       ●                ",
                        "       ▓                ",
                        "       ▓                ",
                        "       ▓                ",
                        "       ▓                ",
                        "       ▓                ",
                        "       ▓                ",
                        "       ▓                ",
                        "       ▓                ",
                        "       ○                ",
                        "       ○                ",
                        "       ○                ",
                        "       ○                ",
                        "       ○                ",
                        "       ○                ",
                        "       ○                ",
                        "       ○                ",
                    ]),
                ["Perpendicular column 8"] = new RenderColumnTestCase(
                    isPerpendicular: true,
                    8,
                    [
                        "        ●               ",
                        "        ●               ",
                        "        ●               ",
                        "        ●               ",
                        "        ●               ",
                        "        ●               ",
                        "        ●               ",
                        "        ●               ",
                        "        ●               ",
                        "        ●               ",
                        "        ▓               ",
                        "        ▓               ",
                        "        ▓               ",
                        "        ▓               ",
                        "        ○               ",
                        "        ○               ",
                        "        ○               ",
                        "        ○               ",
                        "        ○               ",
                        "        ○               ",
                        "        ○               ",
                        "        ○               ",
                        "        ○               ",
                        "        ○               ",
                    ]),
                ["Perpendicular column 9"] = new RenderColumnTestCase(
                    isPerpendicular: true,
                    9,
                    [
                        "         ●              ",
                        "         ●              ",
                        "         ●              ",
                        "         ●              ",
                        "         ●              ",
                        "         ●              ",
                        "         ●              ",
                        "         ●              ",
                        "         ●              ",
                        "         ●              ",
                        "         ▓              ",
                        "         ▓              ",
                        "         ▓              ",
                        "         ▓              ",
                        "         ○              ",
                        "         ○              ",
                        "         ○              ",
                        "         ○              ",
                        "         ○              ",
                        "         ○              ",
                        "         ○              ",
                        "         ○              ",
                        "         ○              ",
                        "         ○              ",
                    ]),
                ["Perpendicular column 10"] = new RenderColumnTestCase(
                    isPerpendicular: true,
                    10,
                    [
                        "          ●             ",
                        "          ●             ",
                        "          ●             ",
                        "          ●             ",
                        "          ●             ",
                        "          ●             ",
                        "          ●             ",
                        "          ●             ",
                        "          ●             ",
                        "          ●             ",
                        "          ●             ",
                        "          ▓             ",
                        "          ▓             ",
                        "          ○             ",
                        "          ○             ",
                        "          ○             ",
                        "          ○             ",
                        "          ○             ",
                        "          ○             ",
                        "          ○             ",
                        "          ○             ",
                        "          ○             ",
                        "          ○             ",
                        "          ○             ",
                    ]),
                ["Perpendicular column 11"] = new RenderColumnTestCase(
                    isPerpendicular: true,
                    11,
                    [
                        "           ●            ",
                        "           ●            ",
                        "           ●            ",
                        "           ●            ",
                        "           ●            ",
                        "           ●            ",
                        "           ●            ",
                        "           ●            ",
                        "           ●            ",
                        "           ●            ",
                        "           ●            ",
                        "                        ",
                        "                        ",
                        "           ○            ",
                        "           ○            ",
                        "           ○            ",
                        "           ○            ",
                        "           ○            ",
                        "           ○            ",
                        "           ○            ",
                        "           ○            ",
                        "           ○            ",
                        "           ○            ",
                        "           ○            ",
                    ]),
                ["Perpendicular column 12"] = new RenderColumnTestCase(
                    isPerpendicular: true,
                    12,
                    [
                        "            ●           ",
                        "            ●           ",
                        "            ●           ",
                        "            ●           ",
                        "            ●           ",
                        "            ●           ",
                        "            ●           ",
                        "            ●           ",
                        "            ●           ",
                        "            ●           ",
                        "            ●           ",
                        "                        ",
                        "                        ",
                        "            ○           ",
                        "            ○           ",
                        "            ○           ",
                        "            ○           ",
                        "            ○           ",
                        "            ○           ",
                        "            ○           ",
                        "            ○           ",
                        "            ○           ",
                        "            ○           ",
                        "            ○           ",
                    ]),
                ["Perpendicular column 13"] = new RenderColumnTestCase(
                    isPerpendicular: true,
                    13,
                    [
                        "             ●          ",
                        "             ●          ",
                        "             ●          ",
                        "             ●          ",
                        "             ●          ",
                        "             ●          ",
                        "             ●          ",
                        "             ●          ",
                        "             ●          ",
                        "             ●          ",
                        "             ●          ",
                        "             ▓          ",
                        "             ▓          ",
                        "             ○          ",
                        "             ○          ",
                        "             ○          ",
                        "             ○          ",
                        "             ○          ",
                        "             ○          ",
                        "             ○          ",
                        "             ○          ",
                        "             ○          ",
                        "             ○          ",
                        "             ○          ",
                    ]),
                ["Perpendicular column 14"] = new RenderColumnTestCase(
                    isPerpendicular: true,
                    14,
                    [
                        "              ●         ",
                        "              ●         ",
                        "              ●         ",
                        "              ●         ",
                        "              ●         ",
                        "              ●         ",
                        "              ●         ",
                        "              ●         ",
                        "              ●         ",
                        "              ●         ",
                        "              ▓         ",
                        "              ▓         ",
                        "              ▓         ",
                        "              ▓         ",
                        "              ○         ",
                        "              ○         ",
                        "              ○         ",
                        "              ○         ",
                        "              ○         ",
                        "              ○         ",
                        "              ○         ",
                        "              ○         ",
                        "              ○         ",
                        "              ○         ",
                    ]),
                ["Perpendicular column 15"] = new RenderColumnTestCase(
                    isPerpendicular: true,
                    15,
                    [
                        "               ●        ",
                        "               ●        ",
                        "               ●        ",
                        "               ●        ",
                        "               ●        ",
                        "               ●        ",
                        "               ●        ",
                        "               ●        ",
                        "               ●        ",
                        "               ●        ",
                        "               ▓        ",
                        "               ▓        ",
                        "               ▓        ",
                        "               ▓        ",
                        "               ○        ",
                        "               ○        ",
                        "               ○        ",
                        "               ○        ",
                        "               ○        ",
                        "               ○        ",
                        "               ○        ",
                        "               ○        ",
                        "               ○        ",
                        "               ○        ",
                    ]),
                ["Perpendicular column 16"] = new RenderColumnTestCase(
                    isPerpendicular: true,
                    16,
                    [
                        "                ●       ",
                        "                ●       ",
                        "                ●       ",
                        "                ●       ",
                        "                ●       ",
                        "                ●       ",
                        "                ●       ",
                        "                ●       ",
                        "                ▓       ",
                        "                ▓       ",
                        "                ▓       ",
                        "                ▓       ",
                        "                ▓       ",
                        "                ▓       ",
                        "                ▓       ",
                        "                ▓       ",
                        "                ○       ",
                        "                ○       ",
                        "                ○       ",
                        "                ○       ",
                        "                ○       ",
                        "                ○       ",
                        "                ○       ",
                        "                ○       ",
                    ]),
                ["Perpendicular column 17"] = new RenderColumnTestCase(
                    isPerpendicular: true,
                    17,
                    [
                        "                 ●      ",
                        "                 ●      ",
                        "                 ●      ",
                        "                 ●      ",
                        "                 ●      ",
                        "                 ●      ",
                        "                 ●      ",
                        "                 ●      ",
                        "                 ▓      ",
                        "                 ▓      ",
                        "                 ▓      ",
                        "                 ▓      ",
                        "                 ▓      ",
                        "                 ▓      ",
                        "                 ▓      ",
                        "                 ▓      ",
                        "                 ○      ",
                        "                 ○      ",
                        "                 ○      ",
                        "                 ○      ",
                        "                 ○      ",
                        "                 ○      ",
                        "                 ○      ",
                        "                 ○      ",
                    ]),
                ["Perpendicular column 18"] = new RenderColumnTestCase(
                    isPerpendicular: true,
                    18,
                    [
                        "                  ●     ",
                        "                  ●     ",
                        "                  ●     ",
                        "                  ●     ",
                        "                  ●     ",
                        "                  ●     ",
                        "                  ●     ",
                        "                  ●     ",
                        "                  ▓     ",
                        "                  ▓     ",
                        "                  ▓     ",
                        "                  ▓     ",
                        "                  ▓     ",
                        "                  ▓     ",
                        "                  ▓     ",
                        "                  ▓     ",
                        "                  ○     ",
                        "                  ○     ",
                        "                  ○     ",
                        "                  ○     ",
                        "                  ○     ",
                        "                  ○     ",
                        "                  ○     ",
                        "                  ○     ",
                    ]),
                ["Perpendicular column 19"] = new RenderColumnTestCase(
                    isPerpendicular: true,
                    19,
                    [
                        "                   ●    ",
                        "                   ●    ",
                        "                   ●    ",
                        "                   ●    ",
                        "                   ●    ",
                        "                   ▓    ",
                        "                   ▓    ",
                        "                   ▓    ",
                        "                   ▓    ",
                        "                   ▓    ",
                        "                   ▓    ",
                        "                   ▓    ",
                        "                   ▓    ",
                        "                   ▓    ",
                        "                   ▓    ",
                        "                   ▓    ",
                        "                   ▓    ",
                        "                   ▓    ",
                        "                   ▓    ",
                        "                   ○    ",
                        "                   ○    ",
                        "                   ○    ",
                        "                   ○    ",
                        "                   ○    ",
                    ]),
                ["Perpendicular column 20"] = new RenderColumnTestCase(
                    isPerpendicular: true,
                    20,
                    [
                        "                    ●   ",
                        "                    ●   ",
                        "                    ●   ",
                        "                    ●   ",
                        "                    ●   ",
                        "                    ▓   ",
                        "                    ▓   ",
                        "                    ▓   ",
                        "                    ▓   ",
                        "                    ▓   ",
                        "                    ▓   ",
                        "                    ▓   ",
                        "                    ▓   ",
                        "                    ▓   ",
                        "                    ▓   ",
                        "                    ▓   ",
                        "                    ▓   ",
                        "                    ▓   ",
                        "                    ▓   ",
                        "                    ○   ",
                        "                    ○   ",
                        "                    ○   ",
                        "                    ○   ",
                        "                    ○   ",
                    ]),
                ["Perpendicular column 21"] = new RenderColumnTestCase(
                    isPerpendicular: true,
                    21,
                    [
                        "                     ●  ",
                        "                     ●  ",
                        "                     ●  ",
                        "                     ●  ",
                        "                     ●  ",
                        "                     ▓  ",
                        "                     ▓  ",
                        "                     ▓  ",
                        "                     ▓  ",
                        "                     ▓  ",
                        "                     ▓  ",
                        "                     ▓  ",
                        "                     ▓  ",
                        "                     ▓  ",
                        "                     ▓  ",
                        "                     ▓  ",
                        "                     ▓  ",
                        "                     ▓  ",
                        "                     ▓  ",
                        "                     ○  ",
                        "                     ○  ",
                        "                     ○  ",
                        "                     ○  ",
                        "                     ○  ",
                    ]),
                ["Perpendicular column 22"] = new RenderColumnTestCase(
                    isPerpendicular: true,
                    22,
                    [
                        "                      ● ",
                        "                      ● ",
                        "                      ● ",
                        "                      ● ",
                        "                      ● ",
                        "                      ▓ ",
                        "                      ▓ ",
                        "                      ▓ ",
                        "                      ▓ ",
                        "                      ▓ ",
                        "                      ▓ ",
                        "                      ▓ ",
                        "                      ▓ ",
                        "                      ▓ ",
                        "                      ▓ ",
                        "                      ▓ ",
                        "                      ▓ ",
                        "                      ▓ ",
                        "                      ▓ ",
                        "                      ○ ",
                        "                      ○ ",
                        "                      ○ ",
                        "                      ○ ",
                        "                      ○ ",
                    ]),
                ["Perpendicular column 23"] = new RenderColumnTestCase(
                    isPerpendicular: true,
                    23,
                    [
                        "                       ●",
                        "                       ▓",
                        "                       ▓",
                        "                       ▓",
                        "                       ▓",
                        "                       ▓",
                        "                       ▓",
                        "                       ▓",
                        "                       ▓",
                        "                       ▓",
                        "                       ▓",
                        "                       ▓",
                        "                       ▓",
                        "                       ▓",
                        "                       ▓",
                        "                       ▓",
                        "                       ▓",
                        "                       ▓",
                        "                       ▓",
                        "                       ▓",
                        "                       ▓",
                        "                       ▓",
                        "                       ▓",
                        "                       ○",
                    ]),
                ["Parallel column 0"] = new RenderColumnTestCase(
                    isPerpendicular: false,
                    0,
                    [
                        "░                       ",
                        "░                       ",
                        "░                       ",
                        "░                       ",
                        "░                       ",
                        "░                       ",
                        "░                       ",
                        "░                       ",
                        "░                       ",
                        "░                       ",
                        "░                       ",
                        "░                       ",
                        "░                       ",
                        "░                       ",
                        "░                       ",
                        "░                       ",
                        "░                       ",
                        "░                       ",
                        "░                       ",
                        "░                       ",
                        "░                       ",
                        "░                       ",
                        "░                       ",
                        "░                       ",
                    ]),
                ["Parallel column 1"] = new RenderColumnTestCase(
                    isPerpendicular: false,
                    1,
                    [
                        " ●                      ",
                        " ░                      ",
                        " ░                      ",
                        " ░                      ",
                        " ░                      ",
                        " ░                      ",
                        " ░                      ",
                        " ░                      ",
                        " ░                      ",
                        " ░                      ",
                        " ░                      ",
                        " ░                      ",
                        " ░                      ",
                        " ░                      ",
                        " ░                      ",
                        " ░                      ",
                        " ░                      ",
                        " ░                      ",
                        " ░                      ",
                        " ░                      ",
                        " ░                      ",
                        " ░                      ",
                        " ░                      ",
                        " ○                      ",
                    ]),
                ["Parallel column 2"] = new RenderColumnTestCase(
                    isPerpendicular: false,
                    2,
                    [
                        "  ●                     ",
                        "  ●                     ",
                        "  ░                     ",
                        "  ░                     ",
                        "  ░                     ",
                        "  ░                     ",
                        "  ░                     ",
                        "  ░                     ",
                        "  ░                     ",
                        "  ░                     ",
                        "  ░                     ",
                        "  ░                     ",
                        "  ░                     ",
                        "  ░                     ",
                        "  ░                     ",
                        "  ░                     ",
                        "  ░                     ",
                        "  ░                     ",
                        "  ░                     ",
                        "  ░                     ",
                        "  ░                     ",
                        "  ░                     ",
                        "  ○                     ",
                        "  ○                     ",
                    ]),
                ["Parallel column 3"] = new RenderColumnTestCase(
                    isPerpendicular: false,
                    3,
                    [
                        "   ●                    ",
                        "   ●                    ",
                        "   ●                    ",
                        "   ░                    ",
                        "   ░                    ",
                        "   ░                    ",
                        "   ░                    ",
                        "   ░                    ",
                        "   ░                    ",
                        "   ░                    ",
                        "   ░                    ",
                        "   ░                    ",
                        "   ░                    ",
                        "   ░                    ",
                        "   ░                    ",
                        "   ░                    ",
                        "   ░                    ",
                        "   ░                    ",
                        "   ░                    ",
                        "   ░                    ",
                        "   ░                    ",
                        "   ○                    ",
                        "   ○                    ",
                        "   ○                    ",
                    ]),
                ["Parallel column 4"] = new RenderColumnTestCase(
                    isPerpendicular: false,
                    4,
                    [
                        "    ●                   ",
                        "    ●                   ",
                        "    ●                   ",
                        "    ●                   ",
                        "    ░                   ",
                        "    ░                   ",
                        "    ░                   ",
                        "    ░                   ",
                        "    ░                   ",
                        "    ░                   ",
                        "    ░                   ",
                        "    ░                   ",
                        "    ░                   ",
                        "    ░                   ",
                        "    ░                   ",
                        "    ░                   ",
                        "    ░                   ",
                        "    ░                   ",
                        "    ░                   ",
                        "    ░                   ",
                        "    ○                   ",
                        "    ○                   ",
                        "    ○                   ",
                        "    ○                   ",
                    ]),
                ["Parallel column 5"] = new RenderColumnTestCase(
                    isPerpendicular: false,
                    5,
                    [
                        "     ●                  ",
                        "     ●                  ",
                        "     ●                  ",
                        "     ●                  ",
                        "     ●                  ",
                        "     ░                  ",
                        "     ░                  ",
                        "     ░                  ",
                        "     ░                  ",
                        "     ░                  ",
                        "     ░                  ",
                        "     ░                  ",
                        "     ░                  ",
                        "     ░                  ",
                        "     ░                  ",
                        "     ░                  ",
                        "     ░                  ",
                        "     ░                  ",
                        "     ░                  ",
                        "     ○                  ",
                        "     ○                  ",
                        "     ○                  ",
                        "     ○                  ",
                        "     ○                  ",
                    ]),
                ["Parallel column 6"] = new RenderColumnTestCase(
                    isPerpendicular: false,
                    6,
                    [
                        "      ●                 ",
                        "      ●                 ",
                        "      ●                 ",
                        "      ●                 ",
                        "      ●                 ",
                        "      ●                 ",
                        "      ░                 ",
                        "      ░                 ",
                        "      ░                 ",
                        "      ░                 ",
                        "      ░                 ",
                        "      ░                 ",
                        "      ░                 ",
                        "      ░                 ",
                        "      ░                 ",
                        "      ░                 ",
                        "      ░                 ",
                        "      ░                 ",
                        "      ○                 ",
                        "      ○                 ",
                        "      ○                 ",
                        "      ○                 ",
                        "      ○                 ",
                        "      ○                 ",
                    ]),
                ["Parallel column 7"] = new RenderColumnTestCase(
                    isPerpendicular: false,
                    7,
                    [
                        "       ●                ",
                        "       ●                ",
                        "       ●                ",
                        "       ●                ",
                        "       ●                ",
                        "       ●                ",
                        "       ●                ",
                        "       ░                ",
                        "       ░                ",
                        "       ░                ",
                        "       ░                ",
                        "       ░                ",
                        "       ░                ",
                        "       ░                ",
                        "       ░                ",
                        "       ░                ",
                        "       ░                ",
                        "       ○                ",
                        "       ○                ",
                        "       ○                ",
                        "       ○                ",
                        "       ○                ",
                        "       ○                ",
                        "       ○                ",
                    ]),
                ["Parallel column 8"] = new RenderColumnTestCase(
                    isPerpendicular: false,
                    8,
                    [
                        "        ●               ",
                        "        ●               ",
                        "        ●               ",
                        "        ●               ",
                        "        ●               ",
                        "        ●               ",
                        "        ●               ",
                        "        ●               ",
                        "        ░               ",
                        "        ░               ",
                        "        ░               ",
                        "        ░               ",
                        "        ░               ",
                        "        ░               ",
                        "        ░               ",
                        "        ░               ",
                        "        ○               ",
                        "        ○               ",
                        "        ○               ",
                        "        ○               ",
                        "        ○               ",
                        "        ○               ",
                        "        ○               ",
                        "        ○               ",
                    ]),
                ["Parallel column 9"] = new RenderColumnTestCase(
                    isPerpendicular: false,
                    9,
                    [
                        "         ●              ",
                        "         ●              ",
                        "         ●              ",
                        "         ●              ",
                        "         ●              ",
                        "         ●              ",
                        "         ●              ",
                        "         ●              ",
                        "         ●              ",
                        "         ░              ",
                        "         ░              ",
                        "         ░              ",
                        "         ░              ",
                        "         ░              ",
                        "         ░              ",
                        "         ○              ",
                        "         ○              ",
                        "         ○              ",
                        "         ○              ",
                        "         ○              ",
                        "         ○              ",
                        "         ○              ",
                        "         ○              ",
                        "         ○              ",
                    ]),
                ["Parallel column 10"] = new RenderColumnTestCase(
                    isPerpendicular: false,
                    10,
                    [
                        "          ●             ",
                        "          ●             ",
                        "          ●             ",
                        "          ●             ",
                        "          ●             ",
                        "          ●             ",
                        "          ●             ",
                        "          ●             ",
                        "          ●             ",
                        "          ●             ",
                        "          ░             ",
                        "          ░             ",
                        "          ░             ",
                        "          ░             ",
                        "          ○             ",
                        "          ○             ",
                        "          ○             ",
                        "          ○             ",
                        "          ○             ",
                        "          ○             ",
                        "          ○             ",
                        "          ○             ",
                        "          ○             ",
                        "          ○             ",
                    ]),
                ["Parallel column 11"] = new RenderColumnTestCase(
                    isPerpendicular: false,
                    11,
                    [
                        "           ●            ",
                        "           ●            ",
                        "           ●            ",
                        "           ●            ",
                        "           ●            ",
                        "           ●            ",
                        "           ●            ",
                        "           ●            ",
                        "           ●            ",
                        "           ●            ",
                        "           ●            ",
                        "           ░            ",
                        "           ░            ",
                        "           ○            ",
                        "           ○            ",
                        "           ○            ",
                        "           ○            ",
                        "           ○            ",
                        "           ○            ",
                        "           ○            ",
                        "           ○            ",
                        "           ○            ",
                        "           ○            ",
                        "           ○            ",
                    ]),
                ["Parallel column 12"] = new RenderColumnTestCase(
                    isPerpendicular: false,
                    12,
                    [
                        "            ●           ",
                        "            ●           ",
                        "            ●           ",
                        "            ●           ",
                        "            ●           ",
                        "            ●           ",
                        "            ●           ",
                        "            ●           ",
                        "            ●           ",
                        "            ●           ",
                        "            ●           ",
                        "            ░           ",
                        "            ░           ",
                        "            ○           ",
                        "            ○           ",
                        "            ○           ",
                        "            ○           ",
                        "            ○           ",
                        "            ○           ",
                        "            ○           ",
                        "            ○           ",
                        "            ○           ",
                        "            ○           ",
                        "            ○           ",
                    ]),
                ["Parallel column 13"] = new RenderColumnTestCase(
                    isPerpendicular: false,
                    13,
                    [
                        "             ●          ",
                        "             ●          ",
                        "             ●          ",
                        "             ●          ",
                        "             ●          ",
                        "             ●          ",
                        "             ●          ",
                        "             ●          ",
                        "             ●          ",
                        "             ●          ",
                        "             ░          ",
                        "             ░          ",
                        "             ░          ",
                        "             ░          ",
                        "             ○          ",
                        "             ○          ",
                        "             ○          ",
                        "             ○          ",
                        "             ○          ",
                        "             ○          ",
                        "             ○          ",
                        "             ○          ",
                        "             ○          ",
                        "             ○          ",
                    ]),
                ["Parallel column 14"] = new RenderColumnTestCase(
                    isPerpendicular: false,
                    14,
                    [
                        "              ●         ",
                        "              ●         ",
                        "              ●         ",
                        "              ●         ",
                        "              ●         ",
                        "              ●         ",
                        "              ●         ",
                        "              ●         ",
                        "              ●         ",
                        "              ░         ",
                        "              ░         ",
                        "              ░         ",
                        "              ░         ",
                        "              ░         ",
                        "              ░         ",
                        "              ○         ",
                        "              ○         ",
                        "              ○         ",
                        "              ○         ",
                        "              ○         ",
                        "              ○         ",
                        "              ○         ",
                        "              ○         ",
                        "              ○         ",
                    ]),
                ["Parallel column 15"] = new RenderColumnTestCase(
                    isPerpendicular: false,
                    15,
                    [
                        "               ●        ",
                        "               ●        ",
                        "               ●        ",
                        "               ●        ",
                        "               ●        ",
                        "               ●        ",
                        "               ●        ",
                        "               ●        ",
                        "               ░        ",
                        "               ░        ",
                        "               ░        ",
                        "               ░        ",
                        "               ░        ",
                        "               ░        ",
                        "               ░        ",
                        "               ░        ",
                        "               ○        ",
                        "               ○        ",
                        "               ○        ",
                        "               ○        ",
                        "               ○        ",
                        "               ○        ",
                        "               ○        ",
                        "               ○        ",
                    ]),
                ["Parallel column 16"] = new RenderColumnTestCase(
                    isPerpendicular: false,
                    16,
                    [
                        "                ●       ",
                        "                ●       ",
                        "                ●       ",
                        "                ●       ",
                        "                ●       ",
                        "                ●       ",
                        "                ●       ",
                        "                ░       ",
                        "                ░       ",
                        "                ░       ",
                        "                ░       ",
                        "                ░       ",
                        "                ░       ",
                        "                ░       ",
                        "                ░       ",
                        "                ░       ",
                        "                ░       ",
                        "                ○       ",
                        "                ○       ",
                        "                ○       ",
                        "                ○       ",
                        "                ○       ",
                        "                ○       ",
                        "                ○       ",
                    ]),
                ["Parallel column 17"] = new RenderColumnTestCase(
                    isPerpendicular: false,
                    17,
                    [
                        "                 ●      ",
                        "                 ●      ",
                        "                 ●      ",
                        "                 ●      ",
                        "                 ●      ",
                        "                 ●      ",
                        "                 ░      ",
                        "                 ░      ",
                        "                 ░      ",
                        "                 ░      ",
                        "                 ░      ",
                        "                 ░      ",
                        "                 ░      ",
                        "                 ░      ",
                        "                 ░      ",
                        "                 ░      ",
                        "                 ░      ",
                        "                 ░      ",
                        "                 ○      ",
                        "                 ○      ",
                        "                 ○      ",
                        "                 ○      ",
                        "                 ○      ",
                        "                 ○      ",
                    ]),
                ["Parallel column 18"] = new RenderColumnTestCase(
                    isPerpendicular: false,
                    18,
                    [
                        "                  ●     ",
                        "                  ●     ",
                        "                  ●     ",
                        "                  ●     ",
                        "                  ●     ",
                        "                  ░     ",
                        "                  ░     ",
                        "                  ░     ",
                        "                  ░     ",
                        "                  ░     ",
                        "                  ░     ",
                        "                  ░     ",
                        "                  ░     ",
                        "                  ░     ",
                        "                  ░     ",
                        "                  ░     ",
                        "                  ░     ",
                        "                  ░     ",
                        "                  ░     ",
                        "                  ○     ",
                        "                  ○     ",
                        "                  ○     ",
                        "                  ○     ",
                        "                  ○     ",
                    ]),
                ["Parallel column 19"] = new RenderColumnTestCase(
                    isPerpendicular: false,
                    19,
                    [
                        "                   ●    ",
                        "                   ●    ",
                        "                   ●    ",
                        "                   ●    ",
                        "                   ░    ",
                        "                   ░    ",
                        "                   ░    ",
                        "                   ░    ",
                        "                   ░    ",
                        "                   ░    ",
                        "                   ░    ",
                        "                   ░    ",
                        "                   ░    ",
                        "                   ░    ",
                        "                   ░    ",
                        "                   ░    ",
                        "                   ░    ",
                        "                   ░    ",
                        "                   ░    ",
                        "                   ░    ",
                        "                   ○    ",
                        "                   ○    ",
                        "                   ○    ",
                        "                   ○    ",
                    ]),
                ["Parallel column 20"] = new RenderColumnTestCase(
                    isPerpendicular: false,
                    20,
                    [
                        "                    ●   ",
                        "                    ●   ",
                        "                    ●   ",
                        "                    ░   ",
                        "                    ░   ",
                        "                    ░   ",
                        "                    ░   ",
                        "                    ░   ",
                        "                    ░   ",
                        "                    ░   ",
                        "                    ░   ",
                        "                    ░   ",
                        "                    ░   ",
                        "                    ░   ",
                        "                    ░   ",
                        "                    ░   ",
                        "                    ░   ",
                        "                    ░   ",
                        "                    ░   ",
                        "                    ░   ",
                        "                    ░   ",
                        "                    ○   ",
                        "                    ○   ",
                        "                    ○   ",
                    ]),
                ["Parallel column 21"] = new RenderColumnTestCase(
                    isPerpendicular: false,
                    21,
                    [
                        "                     ●  ",
                        "                     ●  ",
                        "                     ░  ",
                        "                     ░  ",
                        "                     ░  ",
                        "                     ░  ",
                        "                     ░  ",
                        "                     ░  ",
                        "                     ░  ",
                        "                     ░  ",
                        "                     ░  ",
                        "                     ░  ",
                        "                     ░  ",
                        "                     ░  ",
                        "                     ░  ",
                        "                     ░  ",
                        "                     ░  ",
                        "                     ░  ",
                        "                     ░  ",
                        "                     ░  ",
                        "                     ░  ",
                        "                     ░  ",
                        "                     ○  ",
                        "                     ○  ",
                    ]),
                ["Parallel column 22"] = new RenderColumnTestCase(
                    isPerpendicular: false,
                    22,
                    [
                        "                      ● ",
                        "                      ░ ",
                        "                      ░ ",
                        "                      ░ ",
                        "                      ░ ",
                        "                      ░ ",
                        "                      ░ ",
                        "                      ░ ",
                        "                      ░ ",
                        "                      ░ ",
                        "                      ░ ",
                        "                      ░ ",
                        "                      ░ ",
                        "                      ░ ",
                        "                      ░ ",
                        "                      ░ ",
                        "                      ░ ",
                        "                      ░ ",
                        "                      ░ ",
                        "                      ░ ",
                        "                      ░ ",
                        "                      ░ ",
                        "                      ░ ",
                        "                      ○ ",
                    ]),
                ["Parallel column 23"] = new RenderColumnTestCase(
                    isPerpendicular: false,
                    23,
                    [
                        "                       ░",
                        "                       ░",
                        "                       ░",
                        "                       ░",
                        "                       ░",
                        "                       ░",
                        "                       ░",
                        "                       ░",
                        "                       ░",
                        "                       ░",
                        "                       ░",
                        "                       ░",
                        "                       ░",
                        "                       ░",
                        "                       ░",
                        "                       ░",
                        "                       ░",
                        "                       ░",
                        "                       ░",
                        "                       ░",
                        "                       ░",
                        "                       ░",
                        "                       ░",
                        "                       ░",
                    ]),
            };

        /// <summary>
        /// Tests that the RenderColumn method populates the screen buffer with the
        /// expected characters.
        /// </summary>
        /// <param name="testCaseName">Name of the test case.</param>
        [Theory]
        [MemberData(nameof(RenderColumnTestData))]
        public void RenderColumnTest(string testCaseName)
        {
            // Arrange
            var testCase = RenderColumnTestCases[testCaseName];
            var columnRenderer = new ColumnRenderer();
            var sectionRenderer = new SectionRenderer(columnRenderer);
            var mockConsole = new Mock<IConsole>();
            var mockBorderPainter = new Mock<IBorderPainter>();
            var painter = new MazePainterPovProxy(mockConsole.Object, mockBorderPainter.Object, sectionRenderer)
            {
                InnerSize = new ConsoleSize(
                    MazePainterPovConstants.PainterInnerWidth,
                    MazePainterPovConstants.PainterInnerHeight),
            };

            // Act
            columnRenderer.RenderColumn(painter, testCase.screenX, testCase.isPerpendicular, Direction.North);

            // Assert
            var actualCharacters = painter.PublicScreenBuffer.ToStringArray();
            foreach (var line in actualCharacters)
            {
                output.WriteLine(line);
            }

            actualCharacters.Should().BeEquivalentTo(testCase.expectedCharacters, options =>
                options.WithStrictOrdering());
        }
    }
}
