# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET
permissions: read-all

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Run tests with code coverate
      run: dotnet test --no-build --verbosity normal --collect:"XPlat Code Coverage" --results-directory .\\TestResults

    - name: Display test results directory
      run: dir -r .\\TestResults

    - name: Report code coverage
      uses: codecov/codecov-action@v2
      with:
        files: .\\TestResults\\**\\*.xml
        flags: unittests
        name: codecov-umbrella
