name: Build, run unit tests and check code coverage
permissions: read-all

on:
  push:
    branches: [ "main", "epic/*" ]
  pull_request:
    branches: [ "main", "epic/*" ]

jobs:

  build_and_test_consolegems:
    uses: ./.github/workflows/BuildAndTest.yml
    with:
      FOLDER_UNDER_TEST: "ConsoleGems"
      MODULE_UNDER_TEST: "Sde.ConsoleGems"
      TEST_FOLDER: "ConsoleGems.Test"
      TEST_PROJECT: "ConsoleGems.Test.csproj"

  build_and_test_mazegame:
    uses: ./.github/workflows/BuildAndTest.yml
    with:
      FOLDER_UNDER_TEST: "Demos/MazeGame"
      MODULE_UNDER_TEST: "Sde.MazeGame"
      TEST_FOLDER: "Demos/MazeGame.Test"
      TEST_PROJECT: "MazeGame.Test.csproj"
