on:
  push:
    branches: [ "main", "epic/*" ]
  pull_request:
    branches: [ "main", "epic/*" ]

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      consolegems: ${{ steps.filter.outputs.consolegems }}
      mazegame: ${{ steps.filter.outputs.mazegame }}
    steps:
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            consolegems:
              - 'ConsoleGems/**'
              - 'ConsoleGems.Test/**'
            mazegame:
              - 'Demos/MazeGame/**'
              - 'Demos/MazeGame.Test/**'

  build_and_test_consolegems:
    needs: changes
    if: needs.changes.outputs.consolegems == 'true'
    uses: ./.github/workflows/BuildAndTest.yml
    with:
      FOLDER_UNDER_TEST: "ConsoleGems"
      MODULE_UNDER_TEST: "Sde.ConsoleGems"
      TEST_FOLDER: "ConsoleGems.Test"
      TEST_PROJECT: "ConsoleGems.Test.csproj"

  build_and_test_mazegame:
    needs: changes
    if: needs.changes.outputs.mazegame == 'true'
    uses: ./.github/workflows/BuildAndTest.yml
    with:
      FOLDER_UNDER_TEST: "Demos/MazeGame"
      MODULE_UNDER_TEST: "Sde.MazeGame"
      TEST_FOLDER: "Demos/MazeGame.Test"
      TEST_PROJECT: "MazeGame.Test.csproj"
